{
 "title": "Hasura - Simple Dashboard",
 "description": "Hasura - simple dashboard using custom Python exporter",
 "tags": [
  "hasura",
  "basic"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Hasura Health Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "expr": "hasura_healthy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hasura Metadata Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "hasura_metadata_consistency_status",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hasura Metadata - Inconsistent Objects",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max by (schema, table, name, type, source) (\n  hasura_metadata_inconsistent_object\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}